Repository exercism/cli, pull requests merged in 2018-08, with the labels that each got.

#686 Rename config.Configuration to config.Config
  cmd/configure.go
  cmd/configure_test.go
  cmd/download.go
  cmd/download_test.go
  cmd/open.go
  cmd/submit.go
  cmd/submit_symlink_test.go
  cmd/submit_test.go
  cmd/troubleshoot.go
  cmd/workspace.go
  config/config.go
  config/config_notwin_test.go
  config/config_windows_test.go
  config/configuration.go
Labels: size/small

#682 Detect all exercises in a workspace
  workspace/exercise.go
  workspace/exercise_test.go
  workspace/workspace.go
  workspace/workspace_test.go
Labels: size/small

#650 Fix the encode problem
  cmd/download.go
  cmd/download_test.go
Labels: size/small

#696 Get rid of the workspace.Locate behavior and comms package
  cmd/download.go
  cmd/open.go
  cmd/submit.go
  comms/question.go
  comms/question_test.go
  comms/selection.go
  comms/selection_test.go
  workspace/exercise.go
  workspace/workspace.go
  workspace/workspace_locate_test.go
  workspace/workspace_symlinks_test.go
  workspace/workspace_test.go
Labels: size/small

#704 Fix linting errors in cmd package
  cmd/download.go
Labels: size/small

#705 Distinguish between path and filepath
  cmd/submit.go
  cmd/submit_test.go
  workspace/document.go
  workspace/document_test.go
  workspace/exercise.go
  workspace/exercise_test.go
Labels: size/small

#721 Handle windows filepaths that accidentally got submitted to the server
  cmd/download.go
  cmd/download_test.go
Labels: size/small, type/bug

#720 Make the timeout configurable globally
  api/client.go
  cli/cli.go
  cmd/root.go
  cmd/troubleshoot.go
Labels: size/small, type/workaround

#722 Handle exercise directories with numeric suffixes
  cmd/download.go
  cmd/download_test.go
  workspace/workspace.go
Labels: size/small, type/bug

#724 Update submit error message when submitting a directory
  cmd/submit.go
  cmd/submit_test.go
Labels: size/small, type/enhancement
